const typesAction = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    CHANGE_PAGE: 'CHANGE_PAGE',
    UPDATE_USER_INFO: 'UPDATE_USER_INFO',
    CHANGE_LOCAL_AVATAR: 'CHANGE_LOCAL_AVATAR',
    EMAIL_RESET_PASS: 'EMAIL_RESET_PASS',
    INC_QUANITY_CARTS: 'INC_QUANITY_CARTS',
    DEC_QUANITY_CARTS: 'DEC_QUANITY_CARTS',
    UPDATE_QUANITY_CARTS: 'UPDATE_QUANITY_CARTS',
}

export default typesAction;
